import { useState } from 'react'
import { ArrowDownRight, ArrowRight, ArrowUpRight, Check, ChevronDown, Clock3, Globe2, Menu, Search, ShieldCheck, X } from 'lucide-react'

type Language = 'es' | 'en'

const copy = {
  es: {
    top: ['Laboratorio', 'Imágenes', 'Patología', 'Banco de Sangre', 'Resultados'],
    nav: ['Inicio', 'Nosotros', 'Sucursales', 'Servicios', 'Pruebas', 'Certificaciones', 'Noticias', 'FAQs', 'Contacto'],
    heroEyebrow: 'Diagnóstico que acompaña tu vida', heroTitle: 'Precisión detrás de cada respuesta.', heroText: 'Ciencia clínica de alto nivel, cerca de ti. Resultados confiables para decisiones que importan.', results: 'Ver resultados', branch: 'Encuentra tu sucursal', ready: 'Resultados listos', turnaround: 'Entrega en 24h', quality: 'Calidad certificada',
    actions: ['Ver resultados', 'Encontrar sucursal', 'Explorar pruebas', 'Nuestros servicios'],
    serviceKicker: 'Lo que hacemos', serviceTitle: 'La salud se lee en detalle.', services: ['Laboratorio', 'Imágenes', 'Patología', 'Banco de Sangre', 'Servicio a Domicilio', 'Servicios Corporativos', 'Pruebas de ADN', 'Servicios Internacionales'],
    storyKicker: 'La ciencia detrás', storyTitle: 'Cada muestra cuenta una historia.', storyText: 'Combinamos experiencia, tecnología y un equipo que entiende que detrás de cada resultado hay una persona. Procesos rigurosos para darte claridad cuando más la necesitas.', learn: 'Conoce nuestra historia', stats: [['4M+', 'Pruebas al año'], ['99.9%', 'Precisión'], ['24h', 'Entrega estándar'], ['30+', 'Ubicaciones']],
    branchKicker: 'Siempre cerca', branchTitle: 'Encuentra tu punto de confianza.', search: 'Busca por ciudad o sucursal', cities: ['Ciudad de México', 'Guadalajara', 'Monterrey'], featured: 'Sucursal destacada', branchName: 'Referencia Polanco', hours: 'Lun–Sáb · 06:00–19:00', map: 'Ver mapa', allBranches: 'Ver todas las sucursales',
    certKicker: 'Nuestro estándar', certTitle: 'La confianza también se certifica.', certText: 'Nuestros procesos viven bajo estándares internacionales de calidad, seguridad y trazabilidad.', certs: ['ISO 15189', 'ISO 9001', 'ISO 17025', 'CAP'],
    insightsKicker: 'Salud e información', insightsTitle: 'Entender también es cuidarse.', read: 'Leer historia completa', articles: [{tag:'Prevención', title:'El valor de conocer tus números a tiempo', text:'Pequeñas señales, grandes decisiones.'}, {tag:'Bienestar', title:'Hábitos que protegen tu corazón'}, {tag:'Ciencia', title:'Lo que una muestra puede revelar'}],
    footerText: 'Diagnóstico humano para una vida más clara.', footerLinks: ['Aviso de privacidad', 'Términos y condiciones', 'Trabaja con nosotros'], contact: 'Contáctanos'
  },
  en: {
    top: ['Laboratory', 'Images', 'Pathology', 'Blood Bank', 'Results'], nav: ['Start', 'Us', 'Branches', 'Services', 'Evidence', 'New features', 'Frequently Asked Questions', 'Reference listens to you'], heroEyebrow: 'Diagnostics that stay with you', heroTitle: 'Precision behind every answer.', heroText: 'High-level clinical science, close to you. Reliable results for decisions that matter.', results: 'View results', branch: 'Find a branch', ready: 'Results ready', turnaround: '24h turnaround', quality: 'Certified quality', actions: ['View results', 'Find a branch', 'Explore tests', 'Our services'], serviceKicker: 'What we do', serviceTitle: 'Health is read in detail.', services: ['Laboratory', 'Imaging', 'Pathology', 'Blood Bank', 'Home Service', 'Corporate Services', 'DNA Testing', 'International Services'], storyKicker: 'The science behind it', storyTitle: 'Every sample tells a story.', storyText: 'We combine expertise, technology and a team that understands there is a person behind every result. Rigorous processes give you clarity when you need it most.', learn: 'Our story', stats: [['4M+', 'Tests yearly'], ['99.9%', 'Accuracy'], ['24h', 'Standard delivery'], ['30+', 'Locations']], branchKicker: 'Always close', branchTitle: 'Find your trusted location.', search: 'Search by city or branch', cities: ['Mexico City', 'Guadalajara', 'Monterrey'], featured: 'Featured branch', branchName: 'Referencia Polanco', hours: 'Mon–Sat · 06:00–19:00', map: 'View map', allBranches: 'View all branches', certKicker: 'Our standard', certTitle: 'Trust is certified too.', certText: 'Our processes live under international standards of quality, safety and traceability.', certs: ['ISO 15189', 'ISO 9001', 'ISO 17025', 'CAP'], insightsKicker: 'Health & insights', insightsTitle: 'Understanding is caring for yourself.', read: 'Read full story', articles: [{tag:'Prevention', title:'The value of knowing your numbers early', text:'Small signals, big decisions.'}, {tag:'Wellness', title:'Habits that protect your heart'}, {tag:'Science', title:'What a sample can reveal'}], footerText: 'Human diagnostics for a clearer life.', footerLinks: ['Privacy notice', 'Terms and conditions', 'Work with us'], contact: 'Contact us'
  }
}

export default function App() {
  const [lang, setLang] = useState<Language>('en'); const [menu, setMenu] = useState(false); const t = copy[lang]
  return <main>
    <header className="site-header">
      <div className="utility"><div className="shell utility-inner"><span className="brand" aria-label="Referencia home"><img src="/referencia-logo.webp" alt="Referencia" style={{ height: '28px', objectFit: 'contain', filter: 'brightness(0) invert(1)' }} /></span><div className="utility-links">{t.top.slice(0, 4).map((item, i) => <span style={{cursor: 'default'}} key={item}>{item}{i < 3 && <span className="green-dot" />}</span>)}<span className="result-link" style={{cursor: 'default'}}>{t.top[4]} <ArrowRight size={14}/></span><div className="language"><button className={lang === 'es' ? 'active' : ''} onClick={() => setLang('es')}>ES</button><span>/</span><button className={lang === 'en' ? 'active' : ''} onClick={() => setLang('en')}>EN</button></div></div><button className="menu-button" onClick={() => setMenu(!menu)} aria-label="Toggle menu">{menu ? <X/> : <Menu/>}</button></div></div>
      <nav className={`primary-nav ${menu ? 'open' : ''}`}><div className="shell nav-inner"><div className="mobile-language"><button className={lang === 'es' ? 'active' : ''} onClick={() => setLang('es')}>ES</button><span>/</span><button className={lang === 'en' ? 'active' : ''} onClick={() => setLang('en')}>EN</button></div>{t.nav.map((item, i) => <span key={item} style={{cursor: 'default'}}>{item}{i === 2 ? <ChevronDown size={13}/> : null}</span>)}<button className="nav-search" aria-label="Search"><Search size={18}/></button></div></nav>
    </header>
    <section className="hero" id="inicio"><img src="/hero-lab.png" alt="Scientist working in a clinical laboratory" className="hero-image absolute inset-0 w-full h-full object-cover"/><div className="hero-wash"/><div className="shell hero-content"><div className="hero-copy reveal"><p className="eyebrow light">{t.heroEyebrow}</p><h1>{t.heroTitle}</h1><p className="hero-text">{t.heroText}</p><div className="hero-buttons"><a href="#resultados" className="button button-light">{t.results}<ArrowRight size={17}/></a><a href="#sucursales" className="button button-outline">{t.branch}<ArrowDownRight size={17}/></a></div></div><div className="hero-note hero-note-one"><Check size={16}/><span><strong>{t.ready}</strong><small>Resultados confiables</small></span></div><div className="hero-note hero-note-two"><Clock3 size={16}/><span><strong>{t.turnaround}</strong><small>Para cuidar lo importante</small></span></div><div className="hero-note hero-note-three"><ShieldCheck size={16}/><span><strong>{t.quality}</strong><small>Estándares internacionales</small></span></div></div><div className="hero-index">01 <span /> 04</div></section>
    <section className="action-strip shell" id="resultados">{t.actions.map((a, i) => <a href={i === 1 ? '#sucursales' : '#servicios'} key={a}><span>0{i+1}</span>{a}<ArrowRight size={17}/></a>)}</section>
    <section className="services section shell" id="servicios"><div className="section-heading"><div><p className="eyebrow">{t.serviceKicker}</p><h2>{t.serviceTitle}</h2></div><p className="side-note">{lang === 'es' ? 'Un ecosistema de diagnóstico pensado para acompañarte en cada etapa.' : 'A diagnostic ecosystem designed to support you at every stage.'}</p></div><div className="services-mosaic"><div className="service-feature"><img src="/story-lab.png" alt="Clinical laboratory team" className="absolute inset-0 w-full h-full object-cover"/><div className="image-shade"/><div className="service-label"><span>01</span><h3>{t.services[0]}</h3><ArrowRight/></div></div><div className="service-tile tile-two"><img src="/insight-lab.png" alt="Sample analysis" className="absolute inset-0 w-full h-full object-cover"/><div className="image-shade"/><div className="service-label"><span>02</span><h3>{t.services[1]}</h3><ArrowRight/></div></div><div className="service-list">{t.services.slice(2).map((s,i)=><a href="#contacto" key={s}><span>{String(i+3).padStart(2,'0')}</span>{s}<ArrowUpRight size={18}/></a>)}</div></div></section>
    <section className="story" id="historia"><div className="story-image"><img src="/story-lab.png" alt="Scientists collaborating in a modern laboratory" className="absolute inset-0 w-full h-full object-cover"/><div className="image-shade"/></div><div className="shell story-content"><p className="eyebrow light">{t.storyKicker}</p><h2>{t.storyTitle}</h2><p>{t.storyText}</p><a href="#contacto" className="text-link light-link">{t.learn}<ArrowRight size={17}/></a></div><div className="dna-detail" aria-hidden="true">⌁<br/>⌁<br/>⌁</div></section>
    <section className="stats shell">{t.stats.map(([num,label])=><div className="stat" key={label}><strong>{num}</strong><span>{label}</span></div>)}</section>
    <section className="branches section shell" id="sucursales"><div className="section-heading"><div><p className="eyebrow">{t.branchKicker}</p><h2>{t.branchTitle}</h2></div><div className="branch-search"><Search size={17}/><input placeholder={t.search}/></div></div><div className="branch-layout"><div className="map-art"><div className="map-grid"/><div className="route route-a"/><div className="route route-b"/>{['33%','53%','72%','45%','78%'].map((left,i)=><span className={`marker marker-${i}`} style={{left}} key={i}><span /></span>)}<span className="map-label">CDMX</span><span className="map-label label-two">GDL</span></div><div className="branch-info"><p className="eyebrow">{t.featured}</p><h3>{t.branchName}</h3><p className="muted">Av. Presidente Masaryk 123<br/>{lang === 'es' ? 'Ciudad de México' : 'Mexico City'}</p><div className="hours"><Clock3 size={16}/>{t.hours}</div><div className="branch-buttons"><a href="#contacto" className="button button-green">{t.map}<ArrowRight size={16}/></a><a href="#contacto" className="text-link">{t.allBranches}<ArrowRight size={16}/></a></div></div></div></section>
    <section className="certifications" id="certificaciones"><div className="shell cert-inner"><div><p className="eyebrow light">{t.certKicker}</p><h2>{t.certTitle}</h2><p>{t.certText}</p></div><div className="cert-list">{t.certs.map((c,i)=><div key={c}><span>0{i+1}</span><strong>{c}</strong><Check size={17}/></div>)}</div></div></section>
    <section className="insights section shell" id="insights"><div className="section-heading"><div><p className="eyebrow">{t.insightsKicker}</p><h2>{t.insightsTitle}</h2></div><a href="#contacto" className="text-link">{t.read}<ArrowRight size={17}/></a></div><div className="stories"><article className="story-feature"><img src="/insight-lab.png" alt="Scientist analyzing a sample" className="absolute inset-0 w-full h-full object-cover"/><div className="image-shade"/><div><p>{t.articles[0].tag}</p><h3>{t.articles[0].title}</h3><span>{t.articles[0].text} <ArrowRight size={15}/></span></div></article><div className="story-column"><article><p className="eyebrow">{t.articles[1].tag}</p><h3>{t.articles[1].title}</h3><a href="#contacto"><ArrowUpRight/></a></article><article><p className="eyebrow">{t.articles[2].tag}</p><h3>{t.articles[2].title}</h3><a href="#contacto"><ArrowUpRight/></a></article></div></div></section>
    <footer id="contacto"><div className="shell footer-top"><div><div className="brand footer-brand"><img src="/referencia-logo.webp" alt="Referencia" style={{ height: '28px', objectFit: 'contain' }} /></div><p>{t.footerText}</p></div><a href="mailto:hola@referencia.com" className="footer-contact">{t.contact}<ArrowUpRight/></a></div><div className="shell footer-bottom"><span>© 2026 Referencia Diagnóstico</span><div>{t.footerLinks.map(l=><a href="#contacto" key={l}>{l}</a>)}</div><span className="footer-location"><Globe2 size={14}/> México · 2026</span></div></footer>
  </main>
}
